- hosts: master
  vars_files:
    - conf/config.yml
  handlers:
    - include: handlers/ubuntu.yml
  tasks:
    - include: libs/apt.yml
    - include: libs/hosts.yml
    - include: libs/gluster-server.yml
    - include: libs/mountvolume.yml
    - include: libs/docker.yml
    - include: libs/swarm-master.yml
    - include: libs/portainer.yml

- hosts: node
  vars_files:
    - conf/config.yml
  handlers:
    - include: handlers/ubuntu.yml
  tasks:
    - include: libs/apt.yml
    - include: libs/hosts.yml
    - include: libs/gluster-client.yml
    - include: libs/mountvolume.yml
    - include: libs/docker.yml
    - include: libs/swarm-node.yml


