- hosts: gluster
  vars_files:
    - conf/config.yml
  handlers:
    - include: handlers/ubuntu.yml
  tasks:
#    - include: libs/apt.yml
#    - include: libs/hosts.yml
    - include: libs/gluster-server.yml
